export const top100Films = [
  { label: "The Shawshank Redemption", value: "abc" },
  { label: "The Godfather", value: "abc" },
  { label: "The Godfather: Part II", value: "abc" },
  { label: "The Dark Knight", value: "abc" },
  { label: "12 Angry Men", value: "abc" },
  { label: "Schindler's List", value: "abc" },
  { label: "Pulp Fiction", value: "abc" },
  {
    label: "The Lord of the Rings: The Return of the King",
    value: "abc",
  },
  { label: "The Good, the Bad and the Ugly", value: "abc" },
  { label: "Fight Club", value: "abc" },
  {
    label: "The Lord of the Rings: The Fellowship of the Ring",
    value: "abc",
  },
  {
    label: "Star Wars: Episode V - The Empire Strikes Back",
    value: "abc",
  },
  { label: "Forrest Gump", value: "abc" },
  { label: "Inception", value: "abc" },
  {
    label: "The Lord of the Rings: The Two Towers",
    value: "abc",
  },
  { label: "One Flew Over the Cuckoo's Nest", value: "abc" },
  { label: "Goodfellas", value: "abc" },
  { label: "The Matrix", value: "abc" },
  { label: "Seven Samurai", value: "abc" },
  {
    label: "Star Wars: Episode IV - A New Hope",
    value: "abc",
  },
  { label: "City of God", value: "abc" },
  { label: "Se7en", value: "abc" },
  { label: "The Silence of the Lambs", value: "abc" },
  { label: "It's a Wonderful Life", value: "abc" },
  { label: "Life Is Beautiful", value: "abc" },
  { label: "The Usual Suspects", value: "abc" },
  { label: "Léon: The Professional", value: "abc" },
  { label: "Spirited Away", value: "abc" },
  { label: "Saving Private Ryan", value: "abc" },
  { label: "Once Upon a Time in the West", value: "abc" },
  { label: "American History X", value: "abc" },
  { label: "Interstellar", value: "abc" },
  { label: "Casablanca", value: "abc" },
  { label: "City Lights", value: "abc" },
  { label: "Psycho", value: "abc" },
  { label: "The Green Mile", value: "abc" },
  { label: "The Intouchables", value: "abc" },
  { label: "Modern Times", value: "abc" },
  { label: "Raiders of the Lost Ark", value: "abc" },
  { label: "Rear Window", value: "abc" },
  { label: "The Pianist", value: "abc" },
  { label: "The Departed", value: "abc" },
  { label: "Terminator 2: Judgment Day", value: "abc" },
  { label: "Back to the Future", value: "abc" },
  { label: "Whiplash", value: "abc" },
  { label: "Gladiator", value: "abc" },
  { label: "Memento", value: "abc" },
  { label: "The Prestige", value: "abc" },
  { label: "The Lion King", value: "abc" },
  { label: "Apocalypse Now", value: "abc" },
  { label: "Alien", value: "abc" },
  { label: "Sunset Boulevard", value: "abc" },
  {
    label:
      "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    value: "abc",
  },
  { label: "The Great Dictator", value: "abc" },
  { label: "Cinema Paradiso", value: "abc" },
  { label: "The Lives of Others", value: "abc" },
  { label: "Grave of the Fireflies", value: "abc" },
  { label: "Paths of Glory", value: "abc" },
  { label: "Django Unchained", value: "abc" },
  { label: "The Shining", value: "abc" },
  { label: "WALL·E", value: "abc" },
  { label: "American Beauty", value: "abc" },
  { label: "The Dark Knight Rises", value: "abc" },
  { label: "Princess Mononoke", value: "abc" },
  { label: "Aliens", value: "abc" },
  { label: "Oldboy", value: "abc" },
  { label: "Once Upon a Time in America", value: "abc" },
  { label: "Witness for the Prosecution", value: "abc" },
  { label: "Das Boot", value: "abc" },
  { label: "Citizen Kane", value: "abc" },
  { label: "North by Northwest", value: "abc" },
  { label: "Vertigo", value: "abc" },
  {
    label: "Star Wars: Episode VI - Return of the Jedi",
    value: "abc",
  },
  { label: "Reservoir Dogs", value: "abc" },
  { label: "Braveheart", value: "abc" },
  { label: "M", value: "abc" },
  { label: "Requiem for a Dream", value: "abc" },
  { label: "Amélie", value: "abc" },
  { label: "A Clockwork Orange", value: "abc" },
  { label: "Like Stars on Earth", value: "abc" },
  { label: "Taxi Driver", value: "abc" },
  { label: "Lawrence of Arabia", value: "abc" },
  { label: "Double Indemnity", value: "abc" },
  {
    label: "Eternal Sunshine of the Spotless Mind",
    value: "abc",
  },
  { label: "Amadeus", value: "abc" },
  { label: "To Kill a Mockingbird", value: "abc" },
  { label: "Toy Story 3", value: "abc" },
  { label: "Logan", value: "abc" },
  { label: "Full Metal Jacket", value: "abc" },
  { label: "Dangal", value: "abc" },
  { label: "The Sting", value: "abc" },
  { label: "2001: A Space Odyssey", value: "abc" },
  { label: "Singin' in the Rain", value: "abc" },
  { label: "Toy Story", value: "abc" },
  { label: "Bicycle Thieves", value: "abc" },
  { label: "The Kid", value: "abc" },
  { label: "Inglourious Basterds", value: "abc" },
  { label: "Snatch", value: "abc" },
  { label: "3 Idiots", value: "abc" },
  { label: "Monty Python and the Holy Grail", value: "abc" },
];
