export const leadsDataDummy = [
  {
    id: "12abc234",
    fullName: "Pranab Newar",
    companyName: "ABC Pvt. Ltd.",
    email: "abc@gmail.com",
    phone: 12345755,
    leadSource: "referral",
    companySize: "50-100",
    prefferedContactMethod: "email",
    additionalNotes: "Interested in CRM solutions",
    leadStatus: "new",
    interestedProducts: ["tech", "crm"],
    newsletter: false,
  },
  {
    id: "34xyz678",
    fullName: "John Doe",
    companyName: "XYZ Solutions",
    email: "johndoe@xyz.com",
    phone: 9876543210,
    leadSource: "website",
    companySize: "10-50",
    prefferedContactMethod: "phone",
    additionalNotes: "Looking for SaaS solutions",
    leadStatus: "contacted",
    interestedProducts: ["SaaS", "automation"],
    newsletter: true,
  },
  {
    id: "56lmn890",
    fullName: "Jane Smith",
    companyName: "LMN Enterprises",
    email: "jane.smith@lmn.com",
    phone: 8765432109,
    leadSource: "linkedin",
    companySize: "100-500",
    prefferedContactMethod: "email",
    additionalNotes: "Needs enterprise-level CRM",
    leadStatus: "qualified",
    interestedProducts: ["CRM", "ERP"],
    newsletter: false,
  },
  {
    id: "78pqr456",
    fullName: "Alice Johnson",
    companyName: "PQR Tech",
    email: "alice@pqr.com",
    phone: 7654321098,
    leadSource: "event",
    companySize: "500+",
    prefferedContactMethod: "email",
    additionalNotes: "Interested in AI-based automation",
    leadStatus: "lost",
    interestedProducts: ["AI", "automation"],
    newsletter: true,
  },
];
