// import { createTheme } from "@mui/material/styles";

// export const theme = createTheme({
//   typography: {
//     h1: {
//       fontSize: "2rem",
//       "@media (min-width:600px)": { fontSize: "2.5rem" },
//       "@media (min-width:900px)": { fontSize: "3rem" },
//       "@media (min-width:1200px)": { fontSize: "3.5rem" },
//       "@media (min-width:1536px)": { fontSize: "4rem" },
//     },
//     h2: {
//       fontSize: "1.75rem",
//       "@media (min-width:600px)": { fontSize: "2.25rem" },
//       "@media (min-width:900px)": { fontSize: "2.75rem" },
//       "@media (min-width:1200px)": { fontSize: "3.25rem" },
//       "@media (min-width:1536px)": { fontSize: "3.75rem" },
//     },
//     h3: {
//       fontSize: "1.5rem",
//       "@media (min-width:600px)": { fontSize: "2rem" },
//       "@media (min-width:900px)": { fontSize: "2.5rem" },
//       "@media (min-width:1200px)": { fontSize: "3rem" },
//       "@media (min-width:1536px)": { fontSize: "3.5rem" },
//     },
//     h4: {
//       fontSize: "1.25rem",
//       "@media (min-width:600px)": { fontSize: "1.75rem" },
//       "@media (min-width:900px)": { fontSize: "2.25rem" },
//       "@media (min-width:1200px)": { fontSize: "2.75rem" },
//       "@media (min-width:1536px)": { fontSize: "3.25rem" },
//     },
//     h5: {
//       fontSize: "1.125rem",
//       "@media (min-width:600px)": { fontSize: "1.5rem" },
//       "@media (min-width:900px)": { fontSize: "1.75rem" },
//       "@media (min-width:1200px)": { fontSize: "2rem" },
//       "@media (min-width:1536px)": { fontSize: "2.5rem" },
//     },
//     h6: {
//       fontSize: "1rem",
//       "@media (min-width:600px)": { fontSize: "1.25rem" },
//       "@media (min-width:900px)": { fontSize: "1.5rem" },
//       "@media (min-width:1200px)": { fontSize: "1.75rem" },
//       "@media (min-width:1536px)": { fontSize: "2rem" },
//     },
//     body1: {
//       fontSize: "1rem",
//       "@media (min-width:600px)": { fontSize: "1.125rem" },
//       "@media (min-width:900px)": { fontSize: "1.25rem" },
//       "@media (min-width:1200px)": { fontSize: "1.375rem" },
//       "@media (min-width:1536px)": { fontSize: "1.5rem" },
//     },
//     body2: {
//       fontSize: "0.875rem",
//       "@media (min-width:600px)": { fontSize: "1rem" },
//       "@media (min-width:900px)": { fontSize: "1.125rem" },
//       "@media (min-width:1200px)": { fontSize: "1.25rem" },
//       "@media (min-width:1536px)": { fontSize: "1.375rem" },
//     },
//     subtitle1: {
//       fontSize: "1rem",
//       "@media (min-width:600px)": { fontSize: "1.125rem" },
//       "@media (min-width:900px)": { fontSize: "1.25rem" },
//       "@media (min-width:1200px)": { fontSize: "1.375rem" },
//       "@media (min-width:1536px)": { fontSize: "1.5rem" },
//     },
//     subtitle2: {
//       fontSize: "0.875rem",
//       "@media (min-width:600px)": { fontSize: "1rem" },
//       "@media (min-width:900px)": { fontSize: "1.125rem" },
//       "@media (min-width:1200px)": { fontSize: "1.25rem" },
//       "@media (min-width:1536px)": { fontSize: "1.375rem" },
//     },
//     caption: {
//       fontSize: "0.75rem",
//       "@media (min-width:600px)": { fontSize: "0.875rem" },
//       "@media (min-width:900px)": { fontSize: "1rem" },
//       "@media (min-width:1200px)": { fontSize: "1.125rem" },
//       "@media (min-width:1536px)": { fontSize: "1.25rem" },
//     },
//     overline: {
//       fontSize: "0.75rem",
//       "@media (min-width:600px)": { fontSize: "0.875rem" },
//       "@media (min-width:900px)": { fontSize: "1rem" },
//       "@media (min-width:1200px)": { fontSize: "1.125rem" },
//       "@media (min-width:1536px)": { fontSize: "1.25rem" },
//     },
//     button: {
//       fontSize: "0.875rem",
//       "@media (min-width:600px)": { fontSize: "1rem" },
//       "@media (min-width:900px)": { fontSize: "1.125rem" },
//       "@media (min-width:1200px)": { fontSize: "1.25rem" },
//       "@media (min-width:1536px)": { fontSize: "1.375rem" },
//     },
//   },
// });
